### ISSUE TITLE
Create IAM role for infra deployment

### ISSUE THREAD

**Issue by chriscasto** [metrotranscom/doorway-infra#19]
We need a dedicated role that can be assumed by users or automation that contains all permissions needed for deploying the bloom infrastructure.

**Comment by isaac-looker** [comment]
It seems possible we could add logging when running the tf as an admin to get the API calls, which would get us most of the way to finding out the min permissions- per this [SO post](https://stackoverflow.com/questions/51273227/whats-the-most-efficient-way-to-determine-the-minimum-aws-permissions-necessary )
